#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --name-only HEAD HEAD~ | grep -q '^yarn\.lock$'; then
  echo "yarn.lock has changed. Running yarn install..."
  yarn install
else
  echo "yarn.lock has not changed. Skipping yarn install."
fi
